ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8081

jwt:
  secret: "TMP2lGzHgGcJvKMasHYoKVVz7MIjBzIelqq4n4wHAD7"
  issuer: "velvet-auth"
  audience: "velvet-users"
  realm: "velvet"

database:
  url: "jdbc:postgresql://postgres-auth:5432/velvet_auth"
  user: "postgres"
  password: "postgres"
  driver: "org.postgresql.Driver"
